apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lesson151
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lesson151
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:

      - name: multitool
        image: praqma/network-multitool
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: HTTP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: lesson151
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 9001
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
  namespace: lesson151
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 9002
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: lesson151
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "test-kuber.com"
    http:
      paths:
      - path: "/api"
        pathType: Prefix
        backend:
          service:
            name: service-backend
            port:
              number: 9002
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: service-frontend
            port:
              number: 9001
