apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lesson15
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lesson15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:

      - name: multitool
        image: praqma/network-multitool
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: HTTP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: lesson15
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 9001
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
  namespace: lesson15
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 9002
      targetPort: 8080
---
